/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#050B14",
        "surface-container-high": "#1A2536",
        "tertiary": "#14B8A6",
        "on-primary": "#ffffff",
        "on-primary-container": "#93C5FD",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#2DD4BF",
        "on-background": "#F1F5F9",
        "surface-dim": "#0F172A",
        "on-secondary-fixed": "#F8FAFC",
        "secondary-fixed-dim": "#CBD5E1",
        "on-error": "#ffffff",
        "surface-tint": "#3B82F6",
        "on-tertiary-fixed-variant": "#CCFBF1",
        "on-error-container": "#FDA4AF",
        "surface-container-highest": "#1E293B",
        "on-primary-fixed-variant": "#BFDBFE",
        "secondary-container": "#334155",
        "tertiary-fixed-dim": "#5EEAD4",
        "surface-bright": "#1E293B",
        "error": "#EF4444",
        "primary-fixed-dim": "#60A5FA",
        "on-secondary-fixed-variant": "#E2E8F0",
        "surface": "#0B1120",
        "on-tertiary": "#0B1120",
        "primary-container": "#1E3A8A",
        "surface-container": "#0F172A",
        "surface-container-low": "#0A0F1D",
        "secondary": "#64748B",
        "inverse-surface": "#F1F5F9",
        "secondary-fixed": "#475569",
        "outline-variant": "#334155",
        "background": "#050B14",
        "primary": "#3B82F6",
        "inverse-on-surface": "#0F172A",
        "on-surface-variant": "#94A3B8",
        "error-container": "#7F1D1D",
        "on-primary-fixed": "#EFF6FF",
        "on-tertiary-fixed": "#F0FDFA",
        "inverse-primary": "#1E3A8A",
        "on-secondary-container": "#F8FAFC",
        "on-surface": "#F8FAFC",
        "tertiary-fixed": "#99F6E4",
        "surface-variant": "#1E293B",
        "tertiary-container": "#115E59",
        "outline": "#475569",
        "primary-fixed": "#DBEAFE"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter-dense": "0.5rem",
        "gutter": "0.75rem",
        "space-sm": "0.375rem",
        "space-lg": "0.75rem",
        "margin": "1rem",
        "space-xs": "0.25rem",
        "space-md": "0.5rem",
        "space-xl": "1rem"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
        "code-lg": ["JetBrains Mono"],
        "headline-sm": ["Inter"],
        "headline-xl": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "code-sm": ["JetBrains Mono"],
        "headline-lg": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "code-lg": ["14px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-sm": ["15px", { "lineHeight": "20px", "fontWeight": "600" }],
        "headline-xl": ["28px", { "lineHeight": "34px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["10px", { "lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "code-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "500" }],
        "headline-lg": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "code-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-md": ["13px", { "lineHeight": "18px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
